server:
  port: 8091

service:
  url:
    patientPrescriptionBase: http://localhost:8080/prescription
    patientGetTokenBase: http://localhost:8080/patient
    patientAuthorizationBase: http://localhost:8080/login